Add translation of 04-Accessors-Attributes-Class-Variables
sergogovich/thelittlebookofruby pull request #17
Opened 2017-02-12 22:10 UTC by denysdovhan

Add translation of `04-Accessors-Attributes-Class-Variables.md`

2017-08-16 09:22 UTC, alexclosed commented on chapters/02-Classes-and-Objects.md
>  Я небагато можу зробити з нашим об'єктом хоча б тому, що нічого не запрограмував в класі **MyClass** з якого він був створений.
Я небагато можу зробити з нашим об'єктом хоча б тому, що нічого не запрограмував в класі **MyClass**,(!) з якого він був створений.

2017-08-16 09:22 UTC, alexclosed commented on chapters/02-Classes-and-Objects.md
>  > Насправді, якщо ви створите порожній клас як от `MyClass`, об'єкти створені від нього — не будуть зовсім безкорисними. Усі класи в  Ruby автоматично успадковують функціональність від класу `Object`
**Тож**,(!) наш об'єкт `ob` може використовувати методи класу

2017-08-16 09:22 UTC, alexclosed commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Насправді є простіший та коротший спосіб отримати той же результат. Все що вам потрібно зробити — це скористатись двома спеціальними методами, `attr_reader` та `attr_writer`, а після яких повинен сто
Все,(!) що вам потрібно зробити
скористатись двома спеціальними методами:(!) `attr_reader` та `attr_writer` -(!) після яких повинен стояти символ:

2017-08-16 09:22 UTC, alexclosed commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +>**Символи**: У Ruby символом є ім’я, перед яким стоїть двокрапка. `Symbol` визначений у бібліотеці класів Ruby, щоб відображати імена всередині інтерпретатора Ruby. Вони можуть використовуватись по
Вони можуть використовуватись **по-різному**

2017-08-16 09:22 UTC, alexclosed commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Раніше я сказав, що виклик `attr_reader` з символом насправді створює змінну з тим самим ім’ям, що і у символу.
що і у символ**і**

2017-08-16 09:22 UTC, alexclosed commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Метод `attr_accessor` також робить це. У коді до класу `Thing`, така поведінка не зовсім очевидна, оскільки клас має метод `initialize` явно створює змінні.
У коді до класу `Thing` така поведінка не зовсім очевидна (нема коми)

2017-08-16 09:22 UTC, alexclosed commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Єдиною вказівкою на те, що змінна `@value` існує є визначення аксесора, яке оголошує атрибут `value`:
Єдиною вказівкою на те, що змінна `@value` існує -(!)  є визначення

2017-08-16 09:22 UTC, alexclosed commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Мій код у самому кінці вихідного файлу встановлює значення кожному об’єкту `Treasure`:
**Мій код у кінці**

2017-08-16 09:22 UTC, alexclosed commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Аксесори атрибутів можуть ініціалізувати більше ніж один атрибут за раз, якщо ви передасте їм список символів у вигляді аргументів розділених функціями, ось так:
Аксесори атрибутів можуть ініціалізувати більше,(!) ніж один атрибут

2017-08-16 09:22 UTC, alexclosed commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Тепер, давайте подивимось як використати читачі та записувачі атрибутів у моїй пригодницькій грі. Завантажте програму **`adventure2.rb`**. Ви побачите, що я створив два атрибути класу `Thing`, які до
Тепер, давайте подивимось,(!) як використати читачі

2017-08-16 09:22 UTC, alexclosed commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Два символи `@` на початку імені цієї змінної оголошують, що змінна `@@num_things` є _змінною класу (class variable)_. Змінні, які ми використовували всередині класів дотепер були змінними екземплярі
Змінні, які ми використовували всередині класів,(!) дотепер були змінними екземплярів
об’єкти, що походять від певного класу,(!) поділяють між собою одні й ті ж змінні

2017-08-16 09:22 UTC, alexclosed commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Тут змінна `@@num_things` має зберігати загальне число об’єктів `Thing` у грі. Ми робимо це простим інкрементуванням змінної класу (ми використовуємо `+=` щоб додати до змінної `1`) у методі `initial
ТУТ,(!) змінна

2017-08-16 09:22 UTC, alexclosed commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Ця діаграма показує клас `Thing` (прямокутний), який містить змінну класу `@@num_things` та змінну екземпляру `@name`. Три овали зображують `Thing`–об’єкти – тобто _екземпляри_ класу `Thing`.  Коли о
Проте, коли об’єкт присвоює значення змінній класу `@@num_things`,(!) це значення

2017-08-16 09:22 UTC, alexclosed commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Знайдіть код наприкінці файлу та запустіть програму щоб побачити як ми створили та ініціалізувати всі три об’єкти та використали змінну класу `@@num_things`, щоб загальну кількість об’єктів `Thing`,
Знайдіть код наприкінці файлу та запустіть програму,(!) щоб побачити,(!) як ми створили та ініціалізувати всі три об’єкти

2017-08-17 14:33 UTC, Mariannach requested changes
Останнє речення незрозуміле в кінці

2017-08-17 14:33 UTC, Mariannach commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Тепер, повертаючись до роботи над маленькою пригодницькою грою, яку я програмував раніше… Мені досі не подобається той факт, що в класах повно повторюваного коду для get та set аксесорів. Дайте мені
**Давайте подивимось**, що я можу..

2017-08-17 14:33 UTC, Mariannach commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Мій код у самому кінці вихідного файлу встановлює значення кожному об’єкту `Treasure`:
Об'єкт**І**

2017-08-17 14:33 UTC, Mariannach commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Навіть хоча вона ніде формально не оголошена, змінна `@value` справді існує і ми можемо отримати її числове значення з допомогою get–аксесора:
**якщо** вона ніде не формально...

2017-08-17 14:33 UTC, Mariannach commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Тут змінна `@@num_things` має зберігати загальне число об’єктів `Thing` у грі. Ми робимо це простим інкрементуванням змінної класу (ми використовуємо `+=` щоб додати до змінної `1`) у методі `initial
Використовуємо ,(!) щоб додати до ...

2017-08-17 14:33 UTC, Mariannach commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Ця діаграма показує клас `Thing` (прямокутний), який містить змінну класу `@@num_things` та змінну екземпляру `@name`. Три овали зображують `Thing`–об’єкти – тобто _екземпляри_ класу `Thing`.  Коли о
Об'єкт**А**

2017-08-17 14:33 UTC, Mariannach commented on chapters/04-Accessors-Attributes-Class-Variables.md
> +Знайдіть код наприкінці файлу та запустіть програму щоб побачити як ми створили та ініціалізувати всі три об’єкти та використали змінну класу `@@num_things`, щоб загальну кількість об’єктів `Thing`,
Програму,(!) щоб побачити, (!) як ми..

2017-08-29 23:29 UTC, merged