Add translation of 06-Hashes
sergogovich/thelittlebookofruby pull request #22
Opened 2017-08-16 16:12 UTC by denysdovhan

Ref #8

2017-08-21 07:37 UTC, Mariannach requested changes

2017-08-21 07:37 UTC, Mariannach commented on chapters/06-Hashes.md
> +Масиви надають хороший спосіб індексації елементів колекції за числом, одна можуть бути випадки, коли набагато зручніше індексувати їх по іншому. Якщо, наприклад, ви створювали колекцію рецептів, бул
Одна**к** ..по-іншому(!)

2017-08-21 07:37 UTC, Mariannach commented on chapters/06-Hashes.md
> +Ruby має клас, який дозволяє вам зробити це. Він називається `Hash` (хеш). Він еквівалентний до того, що у інших мовах називають _словником_. Як і справжній словник, елементи індексуються за деяким у
У словнику -(!) це визначення

2017-08-21 07:37 UTC, Mariannach commented on chapters/06-Hashes.md
> +Ruby має клас, який дозволяє вам зробити це. Він називається `Hash` (хеш). Він еквівалентний до того, що у інших мовах називають _словником_. Як і справжній словник, елементи індексуються за деяким у
У словнику- це визначення

2017-08-21 07:37 UTC, Mariannach commented on chapters/06-Hashes.md
> +Моючи створений `Hash`–об’єкт ви можете додавати у нього елементи використовуючи синтаксис схожий на масиви: вказуючи індекс між квадратними дужками та використовуючи `=` для присвоєння значення.
об'єкт,(!) ви можете додавати у нього елементи,(!) використовуючи..

2017-08-21 07:37 UTC, Mariannach commented on chapters/06-Hashes.md
> +Очевидна відмінність тут у тому, що для масивів індексом (_ключем_) має бути ціле число; для хешу це може бути будь-які унікальний елемент даних:
Будь-як**ИЙ**

2017-08-21 07:37 UTC, Mariannach commented on chapters/06-Hashes.md
> +Часто, ключем може бути число або, як у прикладі вище, рядок. В принципі, ключем може бути об’єкт будь–якого типу. Маючи деякий клас, скажімо `X`, таке присвоєння є цілком можливим:
Часто (!) ключем може бути...

2017-08-21 07:37 UTC, Mariannach commented on chapters/06-Hashes.md
> +Методи `keys` (ключі) та `values` (значення) для `Hash` повертають масиви, тож ви можете різні методи масивів, щоб маніпулювати ними. Ось кілька простих прикладів (зауважте, що значення, які отримают
можете **використовувати** різні методи масивів, ..

2017-08-21 07:37 UTC, Mariannach commented on chapters/06-Hashes.md
> +Зверніть особливу увагу на відмінність між конкатенацією з допомогою `+`, щоб додавати значення другого масиву до першого, та додаванням в кінець з допомогою `<<`, щод додавати цілий другий масив як
**щоБ** додавати цілий  другий масив,(!) як останній елемент першого масиву.

2017-08-21 07:37 UTC, Mariannach commented on chapters/06-Hashes.md
> +При додаванні через `<<` перший масив (_приймач_ або _receiver_) модифікується, тоді як `+` повертає новий масив, а масив–приймач залишає незмінненим. Якщо, після додавання в кінець масиву через `<<`
через << ,(!) перший масив ..
Якщо(!) після додавання в кінець масиву через << (!) ви виріш**И**те, що **хочете** додати ..

2017-08-22 16:59 UTC, alexclosed commented on chapters/06-Hashes.md
> +Ви можете створити хеш шляхом створення нового екземпляру класу `Hash`:
екземпляр**а**

2017-08-22 16:59 UTC, alexclosed commented on chapters/06-Hashes.md
> +Моючи створений `Hash`–об’єкт ви можете додавати у нього елементи використовуючи синтаксис схожий на масиви: вказуючи індекс між квадратними дужками та використовуючи `=` для присвоєння значення.
у нього елементи,(!) використовуючи

2017-08-22 16:59 UTC, alexclosed commented on chapters/06-Hashes.md
> +Очевидна відмінність тут у тому, що для масивів індексом (_ключем_) має бути ціле число; для хешу це може бути будь-які унікальний елемент даних:
будь-як**им** унікальн**им** елемент**ом**

2017-08-22 16:59 UTC, alexclosed commented on chapters/06-Hashes.md
> +> Потурбуйтесь про присвоєння ключів в хеші. Якщо ви використовуєте один і той самий ключ двічі, ви перезаписуєте початкове значення. Це те саме, що і двічі присвоїти значення одному й тому ж індексо
розглян**емо**

2017-08-22 16:59 UTC, alexclosed commented on chapters/06-Hashes.md
> +Методи `keys` (ключі) та `values` (значення) для `Hash` повертають масиви, тож ви можете різні методи масивів, щоб маніпулювати ними. Ось кілька простих прикладів (зауважте, що значення, які отримают
що значення, які отримаються в результаті запуску рядка коду,(!) показані

2017-08-29 23:32 UTC, merged